// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'index',
    'history',
    'license',
    {
      type:"link",
      label: 'JavaAPI文档',
      href: 'https://javadoc.io/doc/org.mozilla/rhino',
    },
    { type:"link",
      label: "Kangax兼容表",
      href: 'https://mozilla.github.io/rhino/compat/engines.html',
    },
    { 
      type:"category",
      label:"版本",
      items:[{type: 'autogenerated', dirName: 'releases'}]
    },
    { 
      type:"category",
      label:"文档",
      items:[{type: 'autogenerated', dirName: 'docs'}]
    },
    {
      type: 'category',
      label: '教程',
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: '工具',
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
  ],
   
};

export default sidebars;
